/**
 * Append Google Meet "Notes by Gemini" docs (in "Meet Recordings" folder)
 * into a single Master Google Doc.
 *
 * Piste 1: Optimisation for NotebookLM (Formatting & Participant Extraction).
 */

const CONFIG = {
  MASTER_DOC_ID: 'YOUR_MASTER_DOC_ID_HERE', 
  SOURCE_FOLDER_NAME: 'Meet Recordings',
  SYNC_MARKER: '[SYNCED_TO_NOTEBOOKLM_MASTER_DOC]'
};

/**
 * Main function to sync Meet notes.
 */
function appendMeetNotesToMaster() {
  const masterDocId = PropertiesService.getScriptProperties().getProperty('MASTER_DOC_ID') || CONFIG.MASTER_DOC_ID;

  if (masterDocId === 'YOUR_MASTER_DOC_ID_HERE' || !masterDocId) {
    console.error('Master Doc ID not set. Please set MASTER_DOC_ID in Script Properties or the script.');
    return;
  }

  const folders = DriveApp.getFoldersByName(CONFIG.SOURCE_FOLDER_NAME);
  if (!folders.hasNext()) {
    console.warn(`Source folder not found: ${CONFIG.SOURCE_FOLDER_NAME}`);
    return;
  }
  const meetFolder = folders.next();

  let masterDoc;
  try {
    masterDoc = DocumentApp.openById(masterDocId);
  } catch (e) {
    console.error(`Could not open Master Doc with ID ${masterDocId}: ${e.message}`);
    return;
  }
  const body = masterDoc.getBody();

  const files = meetFolder.getFiles();
  let count = 0;

  while (files.hasNext()) {
    const file = files.next();
    const fileId = file.getId();
    const fileName = file.getName();
    const mime = file.getMimeType();
    const description = file.getDescription() || '';

    if (description.includes(CONFIG.SYNC_MARKER)) {
      continue;
    }

    if (mime !== MimeType.GOOGLE_DOCS) {
      console.log(`Skipping non-Doc file: ${fileName}`);
      file.setDescription(`${description}\n${CONFIG.SYNC_MARKER} (SKIPPED: Not a Google Doc)`.trim());
      continue;
    }

    console.log(`Processing: ${fileName} (${fileId})`);

    try {
      const rawText = exportGoogleDocAsText_(fileId);
      
      // --- PISTE 1: Formatting & Extraction ---
      const participants = extractParticipants_(rawText);
      const cleanedText = cleanGeminiText_(rawText);

      if (body.getText().length > 0) {
        body.appendPageBreak();
      }

      // H2 for Meeting Title (helps NotebookLM segmentation)
      const titlePara = body.appendParagraph(fileName);
      titlePara.setHeading(DocumentApp.ParagraphHeading.HEADING_2);

      // Metadata section
      const datePara = body.appendParagraph(`📅 Date of Meeting: ${file.getDateCreated().toLocaleDateString()}`);
      datePara.setItalic(true).setFontSize(10);
      
      if (participants) {
        const partPara = body.appendParagraph(`👥 Participants: ${participants}`);
        partPara.setHeading(DocumentApp.ParagraphHeading.HEADING_3);
      }

      body.appendParagraph('---').setAttributes({HORIZONTAL_ALIGNMENT: DocumentApp.HorizontalAlignment.CENTER});

      // Append content by paragraphs (splitting by newline for better layout)
      const lines = cleanedText.split('\n');
      lines.forEach(line => {
        if (line.trim()) {
          const p = body.appendParagraph(line.trim());
          // Optional: detected if line looks like a sub-header
          if (line.trim().length < 50 && (line.includes(':') || line.toUpperCase() === line)) {
             p.setBold(true);
          }
        }
      });

      // Mark as processed
      file.setDescription(`${description}\n${CONFIG.SYNC_MARKER}`.trim());
      console.log(`✅ Successfully appended: ${fileName}`);
      count++;

    } catch (e) {
      console.error(`❌ Failed to process ${fileName}: ${e.message}`);
    }
  }

  if (count > 0) {
    console.log(`Sync complete. Appended ${count} meeting(s).`);
  } else {
    console.log('No new meetings found to sync.');
  }
}

/**
 * Extract participants list from the text.
 * Gemini notes usually have a "Participants" or "Attendees" line.
 */
function extractParticipants_(text) {
  const patterns = [
    /Participants:\s*(.*)/i,
    /Attendees:\s*(.*)/i,
    /Présents:\s*(.*)/i
  ];
  
  for (const pattern of patterns) {
    const match = text.match(pattern);
    if (match && match[1]) return match[1].trim();
  }
  return null;
}

/**
 * Remove noise from exported text and prepare for Master Doc.
 */
function cleanGeminiText_(text) {
  // Remove redundant participant lines if we already extracted them
  let cleaned = text.replace(/Participants:\s*(.*)/i, '');
  cleaned = cleaned.replace(/Attendees:\s*(.*)/i, '');
  cleaned = cleaned.replace(/Présents:\s*(.*)/i, '');
  
  // Remove common "Notes by Gemini" headers if they exist in text
  cleaned = cleaned.replace(/Notes generated by Gemini/gi, '');
  
  return cleaned.trim();
}

/**
 * Export a Google Doc as plain text using Drive v3 export endpoint.
 */
function exportGoogleDocAsText_(fileId) {
  const url = `https://www.googleapis.com/drive/v3/files/${fileId}/export?mimeType=text/plain`;
  const token = ScriptApp.getOAuthToken();

  const response = UrlFetchApp.fetch(url, {
    method: 'get',
    headers: { Authorization: `Bearer ${token}` },
    muteHttpExceptions: true
  });

  if (response.getResponseCode() !== 200) {
    throw new Error(`Export API error: ${response.getResponseCode()} - ${response.getContentText()}`);
  }

  return response.getContentText();
}

/**
 * Setup function
 */
function setup() {
  console.log('--- SETUP INSTRUCTIONS ---');
  console.log('1. Go to Project Settings (cog icon).');
  console.log('2. Scroll to "Script Properties".');
  console.log('3. Add a property:');
  console.log('   Property: MASTER_DOC_ID');
  console.log('   Value: [Your Google Doc ID]');
  console.log('4. Ensure you have a folder named "Meet Recordings" in your Drive.');
  console.log('5. Run "appendMeetNotesToMaster" manually once to authorize.');
}
