/**
 * Google Meet Gemini Notes → NotebookLM Sync (Titan v3)
 * 
 * VERSION ULTIME : 100% API JSON. 
 * Performance maximale : Élimination totale de DocumentApp pendant la synchro.
 */

const CONFIG = {
  SOURCE_FOLDER_NAME: 'Meet Recordings', 
  MAX_FILES_PER_RUN: 20,
  ENABLE_NOTIFICATIONS: true
};

function onOpen() {
  try {
    DocumentApp.getUi().createMenu('🚀 NotebookLM')
        .addItem('Sincroniser maintenant', 'appendMeetNotesToMaster')
        .addSeparator()
        .addItem('Réinitialiser l\'état (Reset)', 'resetSyncProperties')
        .addToUi();
  } catch (e) {}
}

/**
 * Synchronisation Ultra-Rapide
 */
function appendMeetNotesToMaster() {
  const docId = DocumentApp.getActiveDocument().getId();
  console.time("Synchro Totale");

  // 1. Trouver le dossier
  const folderId = getFolderIdByName_(CONFIG.SOURCE_FOLDER_NAME);
  if (!folderId) throw new Error("Dossier source non trouvé.");

  // 2. Chercher les fichiers non synchronisés (Recherche indexée Google = Instantané)
  const query = `'${folderId}' in parents and mimeType = 'application/vnd.google-apps.document' and appProperties/synced != 'true'`;
  const result = Drive.Files.list({ q: query, pageSize: CONFIG.MAX_FILES_PER_RUN, fields: "files(id, name, createdTime)" });

  if (!result.files || result.files.length === 0) {
    console.log("Aucune nouvelle réunion.");
    try { DocumentApp.getUi().alert("Tout est déjà à jour !"); } catch(e) {}
    return;
  }

  let requests = [];
  let syncedNames = [];

  // 3. Traitement des fichiers
  for (const file of result.files) {
    try {
      console.log(`Extraction : ${file.name}`);
      const rawText = Drive.Files.export(file.id, 'text/plain').getContentText();
      
      const participants = extractParticipants_(rawText);
      const cleanText = cleanGeminiText_(rawText);
      const date = new Date(file.createdTime).toLocaleDateString();
      
      const block = `\n\n${file.name}\n📅 Date : ${date}\n${participants ? '👥 Participants : ' + participants + '\n' : ''}----------------------------------------------------------\n${cleanText}\n`;

      // Insertion à l'index 1 (Début du doc) -> Beaucoup plus rapide sur gros docs
      requests.push({
        insertText: {
          location: { index: 1 },
          text: block
        }
      });

      // Marquage immédiat (Propriété cachée)
      Drive.Files.update({ appProperties: { synced: "true" } }, file.id);
      syncedNames.push(file.name);
    } catch (e) {
      console.error(`Erreur sur ${file.name}: ${e.message}`);
    }
  }

  // 4. Envoi groupé (Batch Update)
  if (requests.length > 0) {
    console.log("Envoi au document...");
    Docs.Documents.batchUpdate({ requests: requests }, docId);
    
    if (CONFIG.ENABLE_NOTIFICATIONS) sendNotification_(syncedNames, `https://docs.google.com/document/d/${docId}/edit`);
    console.timeEnd("Synchro Totale");
    try { DocumentApp.getUi().alert(`✅ ${syncedNames.length} réunion(s) ajoutée(s) au début du document.`); } catch(e) {}
  }
}

/**
 * Reset complet de l'état de synchronisation
 */
function resetSyncProperties() {
  const ui = DocumentApp.getUi();
  if (ui.alert('Confirmation', 'Voulez-vous tout ré-importer ?', ui.ButtonSet.YES_NO) !== ui.Button.YES) return;

  const folderId = getFolderIdByName_(CONFIG.SOURCE_FOLDER_NAME);
  const files = Drive.Files.list({ q: `'${folderId}' in parents`, fields: "files(id)" }).files;

  for (const file of files) {
    Drive.Files.update({ appProperties: { synced: "false" } }, file.id);
  }
  ui.alert("🔄 Prêt pour ré-importation.");
}

function getFolderIdByName_(name) {
  const res = Drive.Files.list({ q: `name = '${name}' and mimeType = 'application/vnd.google-apps.folder' and trashed = false`, fields: "files(id)" });
  return res.files && res.files.length > 0 ? res.files[0].id : null;
}

function extractParticipants_(text) {
  const m = text.match(/(?:Participants|Attendees|Présents):\s*(.*)/i);
  return m ? m[1].trim() : null;
}

function cleanGeminiText_(text) {
  return text.replace(/(?:Participants|Attendees|Présents):\s*(.*)/i, '')
             .replace(/Notes par Gemini.*/gi, '')
             .replace(/Notes generated by Gemini/gi, '')
             .trim();
}

function sendNotification_(meetings, url) {
  const email = Session.getActiveUser().getEmail() || Session.getEffectiveUser().getEmail();
  MailApp.sendEmail(email, `✅ Synchro NotebookLM (${meetings.length})`, `Réunions ajoutées :\n\n- ${meetings.join('\n- ')}\n\nDoc : ${url}`);
}
